# Rename this to 'config.yml' and fill in your data

# Your MySQL credentials
mysql:
  host: localhost
  port: 3306
  user: YOUR_MYSQL_USER
  password: YOUR_MYSQL_PASSWORD
  db: YOUR_MYSQL_DB_NAME

webserver:
  # The address and port the webserver is supposed to bind to
  address_and_port: '127.0.0.1:4000'
  # A token that you can provide in a request's authorization header to use the API without a session (cookie)
  # In a future version, there'll be an option to create multiple access tokens on the web interface
  # Read more: https://github.com/fabiancdng/GoShortrr/wiki/REST-API
  api_access_token: ''