name: Build and deploy Docker image to ghcr.io

on:
  push:
    tags:
      - 'v*'

jobs:
  docker-deploy:
    name: Docker Image Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/fabiancdng/goshortrr:latest
            ghcr.io/fabiancdng/goshortrr:${{ steps.get_version.outputs.VERSION }}